version: '3.9'

services:
  profilerpg:
    image: postgres
    restart: always
    container_name: profiler_psql
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - $POSTGRES_HOST_PORT:5432
    volumes:
      - $PWD/custom:/custom
      - $PWD/custom/init.sql:/docker-entrypoint-initdb.d/init.sql
      - $PWD/profiler/data/postgresql:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    container_name: profiler_redis
    ports:
      - $REDIS_HOST_PORT:6379
    depends_on:
      - profilerpg

  serve:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: supervisord
    container_name: profiler_app
    volumes:
      - .:/var/www/
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_HOST_PORT: $POSTGRES_HOST_PORT

      FLASK_SKIP_DOTENV: $FLASK_SKIP_DOTENV
      FLASK_ENV: $FLASK_ENV
      FLASK_APP: $FLASK_APP
      FLASK_DEBUG: $FLASK_DEBUG
      FLASK_RUN_HOST: $FLASK_RUN_HOST

      REDIS_HOST: $REDIS_HOST
      REDIS_HOST_PORT: $REDIS_HOST_PORT
      REDIS_DB: $REDIS_DB

      SITE_NAME: $SITE_NAME
      SECRET_KEY: $SECRET_KEY
      PROFILER_STATUS: $PROFILER_STATUS

    ports:
      - $SERVER_HOST_PORT:80
      - $DEV_SERVER_HOST_PORT:5000
      - $SUPERVISOR_HOST_PORT:9001
    depends_on:
      - profilerpg